Repository amandou/Jame-Gam-Christmas-Edition, pull requests merged in 2022-12, with the labels that each got.

#16 Create basic cards mechanics
  Christmas Builder/Assets/Bar.png
  Christmas Builder/Assets/Bar.png.meta
  Christmas Builder/Assets/Plugins.meta
  Christmas Builder/Assets/Plugins/Demigiant.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/DOTween.XML
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/DOTween.XML.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/DOTween.dll.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Editor.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.XML
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.XML.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.dll.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Editor/Imgs.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenIcon.png
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenIcon.png.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenMiniIcon.png
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenMiniIcon.png.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer.png
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer.png.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer_dark.png
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer_dark.png.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Header.jpg
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Header.jpg.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleAudio.cs
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleAudio.cs.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleEPOOutline.cs
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleEPOOutline.cs.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics.cs
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics.cs.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics2D.cs
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics2D.cs.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleSprite.cs
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleSprite.cs.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUI.cs
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUI.cs.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUnityVersion.cs
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUnityVersion.cs.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUtils.cs
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUtils.cs.meta
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/readme.txt
  Christmas Builder/Assets/Plugins/Demigiant/DOTween/readme.txt.meta
  Christmas Builder/Assets/Prefabs.meta
  Christmas Builder/Assets/Prefabs/Card.prefab
  Christmas Builder/Assets/Prefabs/Card.prefab.meta
  Christmas Builder/Assets/Resources.meta
  Christmas Builder/Assets/Resources/DOTweenSettings.asset
  Christmas Builder/Assets/Resources/DOTweenSettings.asset.meta
  Christmas Builder/Assets/Scenes/CardMechanics.unity
  Christmas Builder/Assets/Scenes/CardMechanics.unity.meta
  Christmas Builder/Assets/Scripts/Card.cs
  Christmas Builder/Assets/Scripts/Card.cs.meta
  Christmas Builder/Assets/Scripts/ConfirmButton.cs
  Christmas Builder/Assets/Scripts/ConfirmButton.cs.meta
  Christmas Builder/Assets/Scripts/FadeAnimation.cs
  Christmas Builder/Assets/Scripts/FadeAnimation.cs.meta
  Christmas Builder/Assets/Scripts/GameManager.cs
  Christmas Builder/Assets/Scripts/GameManager.cs.meta
  Christmas Builder/ProjectSettings/ProjectSettings.asset
  Christmas Builder/UserSettings/Layouts/default-2021.dwlt
Labels: feature

#19 Gets child values from letters
  Christmas Builder/Assets/Localization/Table Collections/Deeds/Deeds Shared Data.asset
  Christmas Builder/Assets/Localization/Table Collections/Wish/Wish Shared Data.asset
  Christmas Builder/Assets/Localization/Table Collections/Wish/Wish_en.asset
  Christmas Builder/Assets/Localization/Table Collections/Wish/Wish_es.asset
  Christmas Builder/Assets/Localization/Table Collections/Wish/Wish_pt.asset
  Christmas Builder/Assets/Scenes/CardMechanics.unity
  Christmas Builder/Assets/Scripts/ConfirmButton.cs
  Christmas Builder/Assets/Scripts/GameManager.cs
  Christmas Builder/Assets/Scripts/Letters/LetterGenerator.cs
Labels: enhancement, feature

#21 Adds music, some images and fixes build issues
  Christmas Builder/Assets/AddressableAssetsData/ProfileDataSourceSettings.asset
  Christmas Builder/Assets/AddressableAssetsData/ProfileDataSourceSettings.asset.meta
  Christmas Builder/Assets/AddressableAssetsData/Windows.meta
  Christmas Builder/Assets/AddressableAssetsData/Windows/addressables_content_state.bin
  Christmas Builder/Assets/AddressableAssetsData/Windows/addressables_content_state.bin.meta
  Christmas Builder/Assets/Music.meta
  Christmas Builder/Assets/Music/Adeline Yeo (HP) - Tis The Season To Be Jolly.mp3
  Christmas Builder/Assets/Music/Adeline Yeo (HP) - Tis The Season To Be Jolly.mp3.meta
  Christmas Builder/Assets/Scenes/CardMechanics.unity
  Christmas Builder/Assets/ScriptableObjectData/Cards/playstadionV.asset
  Christmas Builder/Assets/ScriptableObjectData/Cards/soccerball.asset
  Christmas Builder/Assets/Scripts/CSVManager/CSVDatabaseLoader.cs
  Christmas Builder/Assets/Scripts/Card.cs
  Christmas Builder/Assets/Scripts/Cards/CardDataSO.cs
  Christmas Builder/Assets/Scripts/Letters/LetterDataSO.cs
  Christmas Builder/Assets/Sprites/weihnachten-hintergrund-karte-1670431145CVB.jpg
  Christmas Builder/Assets/Sprites/weihnachten-hintergrund-karte-1670431145CVB.jpg.meta
  Christmas Builder/Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Anton SDF.asset
  Christmas Builder/Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
  Christmas Builder/Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
  Christmas Builder/Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Oswald Bold SDF.asset
  Christmas Builder/Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Roboto-Bold SDF.asset
  Christmas Builder/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Christmas Builder/ProjectSettings/BurstAotSettings_StandaloneWindows.json
  Christmas Builder/ProjectSettings/CommonBurstAotSettings.json
  Christmas Builder/ProjectSettings/EditorBuildSettings.asset
  Christmas Builder/UserSettings/EditorUserSettings.asset
  Christmas Builder/UserSettings/Layouts/default-2021.dwlt
Labels: bug, enhancement, feature
